# Generated by Django 5.0.2 on 2024-02-27 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Men', 'Men'), ('Women', 'Women'), ('Child', 'Child')], max_length=20, null=True)),
                ('size', models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL')], max_length=20, null=True)),
                ('brand', models.CharField(choices=[('Levis', 'Levis'), ('Roadstar', 'Roadstar'), ('Nike', 'Nike')], max_length=20, null=True)),
                ('price', models.IntegerField()),
                ('desc', models.TextField()),
                ('ppicture', models.ImageField(default='', upload_to='ppicture')),
                ('pname', models.CharField(max_length=20)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
