# Generated by Django 5.0.2 on 2024-03-18 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_cart_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='product_price',
            new_name='price',
        ),
    ]
