# Generated by Django 5.0.2 on 2024-03-22 10:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='myapp.cart'),
            preserve_default=False,
        ),
    ]
