# Generated by Django 5.0.2 on 2024-03-24 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_option_product_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='options',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
    ]
