# Generated by Django 5.0.2 on 2024-03-27 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_product_options_delete_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='tprice',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
