# Generated by Django 5.0.2 on 2024-03-27 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_orderitem_tprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='tprice',
        ),
    ]
